trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
      curl -s "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip && unzip dependency-check.zip && rm dependency-check.zip
      dependency-check/bin/dependency-check.sh --out ''$(Build.ArtifactStagingDirectory)/dependency-check-result.json'' --format JSON --scan $(System.DefaultWorkingDirectory)
    displayName: "Run Dependency Check"
